<?php
pdo_query("DROP TABLE IF EXISTS `ims_haoman_virtuamall_addcard`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_address`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_adv`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_cardticket`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_cart`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_category`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_dispatch`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_express`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_feedback`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_goods`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_goods_option`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_goods_param`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_hexiaoaward`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_hexiaopeople`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_order`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_order_goods`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_pici`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_product`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_pw`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_spec`;
DROP TABLE IF EXISTS `ims_haoman_virtuamall_spec_item`;
");
