<?php

$sql =<<<EOF
CREATE TABLE `ims_cgc_baoming_activity` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(3) NOT NULL,
  `uniacid` int(3) NOT NULL,
  `logo` varchar(200) NOT NULL DEFAULT '' COMMENT '图片',
  `title` varchar(100) NOT NULL DEFAULT '' COMMENT '标题',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '状态 0 正常，1结束',
  `cj_code` varchar(100) NOT NULL DEFAULT '' COMMENT '抽奖码',
  `start_time` int(10) NOT NULL COMMENT '开始时间',
  `end_time` int(10) NOT NULL COMMENT '结束时间',
  `kj_time` int(10) NOT NULL COMMENT '开奖时间',
  `succ_url` text NOT NULL COMMENT '报名成功自定义说明链接',
  `end_url` text NOT NULL COMMENT '活动结束跳转链接',
  `cj_code_start` int(10) DEFAULT '0' COMMENT '用户抽奖码初始值',
  `share_title` varchar(100) NOT NULL DEFAULT '' COMMENT '分享标题',
  `share_url` text NOT NULL COMMENT '分享url',
  `share_thumb` varchar(200) NOT NULL DEFAULT '' COMMENT '分享图片',
  `bottom_guide` varchar(200) NOT NULL DEFAULT '' COMMENT '分享页面底部图片',
  `share_desc` varchar(100) NOT NULL DEFAULT '' COMMENT '描述',
  `share_guide_text` text NOT NULL COMMENT '分享页面自定义文字',
  `share_guide_image` varchar(200) NOT NULL DEFAULT '' COMMENT '分享页面自定义图片',
  `award_mode` int(1) NOT NULL DEFAULT '0' COMMENT '0，默认，1，随机中奖',
  `award_url` varchar(300) NOT NULL DEFAULT '' COMMENT '中奖跳转',
  `award_info` varchar(300) NOT NULL DEFAULT '' COMMENT '中奖提示',
  `award_chance` int(3) NOT NULL DEFAULT '0' COMMENT '中奖几率',
  `not_award_url` varchar(200) NOT NULL DEFAULT '' COMMENT '未中奖跳转',
  `not_award_info` varchar(300) NOT NULL DEFAULT '' COMMENT '未中奖提示',
  `tel_show` int(1) NOT NULL DEFAULT '0' COMMENT '0，默认，1，显示',
  `addr_show` int(1) NOT NULL DEFAULT '0' COMMENT '0，默认，1，显示',
  `realname_show` int(1) NOT NULL DEFAULT '0' COMMENT '0，默认，1，显示',
  `wechat_no_show` int(1) NOT NULL DEFAULT '0' COMMENT '0，默认，1，显示',
  `share_guide` varchar(200) NOT NULL DEFAULT '' COMMENT '分享页面图片',
  `share_guide_info` text NOT NULL COMMENT '分享页面文字',
  `code_type` int(1) NOT NULL DEFAULT '0' COMMENT '0，需要分享，1，不需要分享',
  `tj_sys` int(1) NOT NULL DEFAULT '0' COMMENT '0，用户资料不写入系统表，1，用户资料是写入系统表',
  `credit1_sys` int(10) NOT NULL DEFAULT '0' COMMENT '积分设置',
  `candidate_sys` int(1) NOT NULL DEFAULT '0' COMMENT '0，不显示新的候选名单，1，显示新的候选名单',
  `must_guanzhu` int(1) NOT NULL DEFAULT '0' COMMENT '是否必须关注才可以报名.0.否.1.是',
  `must_guanzhu_msg` varchar(50) NOT NULL DEFAULT '' COMMENT '关注提示语',
  `rule` text NOT NULL COMMENT '活动规则',
  `jp_mc` varchar(200) NOT NULL DEFAULT '' COMMENT '奖品名称',
  `template_id` varchar(200) NOT NULL DEFAULT '' COMMENT '模板id',
  `new_wxtx` text NOT NULL COMMENT '微信id',
  `pay_flag` int(1) NOT NULL DEFAULT '0' COMMENT '报名是否需要支付0:不需要,1需要',
  `pay_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `pay_num` int(10) NOT NULL DEFAULT '0' COMMENT '可支付数量',
  `pay_numed` int(10) NOT NULL DEFAULT '0' COMMENT '已支付数量',
  `activity_type` int(2) NOT NULL DEFAULT '0' COMMENT '报名类型（0：抽奖券、1：优惠券、2：支付订单）',
  `hx_pass` varchar(50) NOT NULL DEFAULT '' COMMENT '核销密码',
  `top_desc` text NOT NULL COMMENT '抽奖或者支付描述',
  `redbag_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '红包金额',
  `redbag_flag` int(2) NOT NULL DEFAULT '0' COMMENT '中奖以后是否发红包(0:不,1:是)',
  `createtime` int(10) DEFAULT NULL,
  `iplimit` varchar(200) DEFAULT '',
  `locationtype` int(1) DEFAULT '0',
  `zdyurl` varchar(300) DEFAULT '',
  `share_type` int(1) DEFAULT '0',
  `join_num` int(10) DEFAULT '0',
  `yq_mode` int(1) DEFAULT '0',
  `my_mode` int(1) DEFAULT '0',
  `max_yq_num` int(10) DEFAULT '0',
  `index_logo` varchar(200) DEFAULT '',
  `xl_num` int(10) DEFAULT '0',
  `max_cj_code` int(10) DEFAULT '0',
  `hx_password` varchar(200) DEFAULT '',
  `ewei_shop` int(1) DEFAULT '0',
  `jh_bg` varchar(500) DEFAULT '',
  `jh_qrcode` varchar(500) DEFAULT '',
  `jh_desc` varchar(500) DEFAULT '',
  `jh_nickname` varchar(50) DEFAULT '',
  `new_login_mode` int(1) DEFAULT '0',
  `cjm_interval` int(10) DEFAULT '0',
  `wxtx` text,
  `newx_wxtx` text,
  `bm_wxtx` text,
  `total_zj` int(10) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_baoming_code` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(10) unsigned NOT NULL,
  `code_id` int(10) NOT NULL,
  `activity_id` int(10) NOT NULL,
  `createtime` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_baoming_fans` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `headimgurl` varchar(200) NOT NULL COMMENT '头像',
  `openid` varchar(100) NOT NULL COMMENT '微信id',
  `nickname` varchar(200) NOT NULL COMMENT '昵称',
  `tel` varchar(11) NOT NULL COMMENT '手机号',
  `realname` varchar(11) NOT NULL COMMENT '真实姓名',
  `sex` int(1) NOT NULL COMMENT '性别',
  `city` varchar(20) NOT NULL COMMENT '城市',
  `province` varchar(10) NOT NULL COMMENT '省份',
  `subscribe` int(1) NOT NULL COMMENT '是否关注',
  `status` int(1) NOT NULL COMMENT '状态 0,未报名,1,已报名.2,已分享',
  `share_num` int(5) NOT NULL COMMENT '分享次数',
  `cjcode_num` int(5) NOT NULL COMMENT '抽奖码次数',
  `parent_openid` varchar(100) NOT NULL COMMENT '上线openid',
  `createtime` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `cgc_baoming_fans_ground` (`uniacid`,`openid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `ims_cgc_baoming_reply` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `rid` int(3) NOT NULL,
  `uniacid` int(3) NOT NULL,
  `activity_id` int(5) NOT NULL,
  `activity_name` varchar(200) NOT NULL,
  `type` int(5) NOT NULL,
  `createtime` int(10) DEFAULT NULL,
  `pic_title` varchar(100) NOT NULL DEFAULT '' COMMENT '分享标题',
  `pic_thumb` varchar(100) NOT NULL DEFAULT '' COMMENT '分享图片',
  `pic_desc` varchar(100) NOT NULL DEFAULT '' COMMENT '描述',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `ims_cgc_baoming_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uniacid` int(3) NOT NULL,
  `activity_id` int(5) NOT NULL COMMENT '报名id',
  `qishu` int(5) NOT NULL COMMENT '第几期',
  `headimgurl` varchar(200) NOT NULL COMMENT '头像',
  `openid` varchar(100) NOT NULL COMMENT '微信id',
  `nickname` varchar(200) NOT NULL COMMENT '昵称',
  `tel` varchar(11) NOT NULL COMMENT '手机号',
  `realname` varchar(11) NOT NULL COMMENT '真实姓名',
  `sex` int(1) NOT NULL COMMENT '性别',
  `city` varchar(20) NOT NULL COMMENT '城市',
  `province` varchar(10) NOT NULL COMMENT '省份',
  `subscribe` int(1) NOT NULL COMMENT '是否关注',
  `status` int(1) NOT NULL DEFAULT '0' COMMENT '用户状态 0 正常，1黑名单',
  `share_status` int(1) NOT NULL DEFAULT '0' COMMENT '分享状态 0未分享，1已分享',
  `cj_code` varchar(100) NOT NULL DEFAULT '' COMMENT '抽奖码',
  `zj_status` int(1) NOT NULL DEFAULT '0' COMMENT '中奖状态 0未中奖，1已中奖',
  `createtime` int(10) DEFAULT NULL,
  `addr` varchar(300) DEFAULT NULL,
  `wechat_no` varchar(50) DEFAULT NULL,
  `yq_type` int(1) DEFAULT '0' COMMENT '0默认，1邀请获得的抽奖码,2朋友圈获得',
  `parent_id` varchar(50) DEFAULT '' COMMENT '父亲openid',
  `byq_openid` varchar(50) DEFAULT '' COMMENT '被邀请openid',
  `byq_nickname` varchar(50) DEFAULT '' COMMENT '被邀请人昵称',
  `hx_status` int(1) DEFAULT '0',
  `is_pay` int(1) DEFAULT '0' COMMENT '是否支付0未支付,1已支付',
  `pay_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '支付金额',
  `ordersn` varchar(50) DEFAULT '' COMMENT '订单号',
  `wx_ordersn` varchar(50) DEFAULT '' COMMENT '微信订单号',
  `is_redbag` int(1) DEFAULT '0' COMMENT '红包发送状态',
  `redbag_money` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '红包金额',
  PRIMARY KEY (`id`),
  KEY `cgc_baoming_user_ground3` (`uniacid`,`activity_id`),
  KEY `cgc_baoming_user_ground4` (`uniacid`,`activity_id`,`openid`),
  KEY `cgc_baoming_user_groundnew` (`uniacid`,`activity_id`,`cj_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

EOF;
pdo_run($sql);
