<?php
pdo_query("CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_ad` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`title` varchar(100) NOT NULL,
`url` varchar(200) NOT NULL,
`thumb` varchar(500) NOT NULL,
`position` tinyint(1) NOT NULL,
`starttime` int(10) NOT NULL,
`endtime` int(10) NOT NULL,
`displayorder` int(10) unsigned NOT NULL,
`status` tinyint(1) NOT NULL,
`dateline` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_article` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`fansid` int(10) unsigned NOT NULL,
`from_user` varchar(50),
`uniacid` int(10) unsigned NOT NULL,
`title` varchar(100) NOT NULL,
`url` varchar(2000) NOT NULL,
`sharecount` int(10) unsigned NOT NULL,
`readcount` int(10) unsigned NOT NULL,
`recommend` tinyint(1) unsigned NOT NULL,
`default_read` int(10) unsigned NOT NULL,
`default_praise` int(10) unsigned NOT NULL,
`status` tinyint(1) unsigned NOT NULL,
`displayorder` int(10) unsigned NOT NULL,
`dateline` int(10) unsigned NOT NULL,
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_fans` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(11),
`from_user` varchar(50),
`nickname` varchar(50),
`headimgurl` varchar(500),
`username` varchar(50),
`mobile` varchar(50),
`address` varchar(200),
`sex` tinyint(1) unsigned NOT NULL,
`country` varchar(50),
`province` varchar(50),
`city` varchar(50),
`lat` decimal(18,10) NOT NULL,
`lng` decimal(18,10) NOT NULL,
`qrcode` varchar(500),
`ad` varchar(500),
`title1` varchar(500),
`title2` varchar(500),
`ad_url` varchar(500),
`starttime` int(10) NOT NULL,
`endtime` int(10) NOT NULL,
`is_vip` tinyint(1),
`status` tinyint(1),
`dateline` int(10),
`admode` tinyint(1) NOT NULL,
`lasttime` varchar(500),
PRIMARY KEY (`id`),
KEY `indx_rid` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`fansid` int(10) unsigned NOT NULL,
`from_user` varchar(50) NOT NULL,
`transid` varchar(50) NOT NULL,
`ordersn` varchar(30) NOT NULL,
`totalprice` varchar(10) NOT NULL,
`ispay` tinyint(1) NOT NULL,
`paytype` tinyint(1) unsigned NOT NULL,
`username` varchar(50) NOT NULL,
`address` varchar(250) NOT NULL,
`tel` varchar(50) NOT NULL,
`status` tinyint(4) NOT NULL,
`remark` varchar(1000) NOT NULL,
`isfinish` tinyint(1) NOT NULL,
`dateline` int(10) unsigned NOT NULL,
`vipcount` int(10) unsigned,
`isdeleted` varchar(500),
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_setting` (
`id` int(10) NOT NULL AUTO_INCREMENT,
`uniacid` int(10) unsigned NOT NULL,
`title` varchar(20),
`is_show_ad` tinyint(1) unsigned NOT NULL,
`is_pay` tinyint(1) unsigned NOT NULL,
`price` varchar(20),
`help` text,
`btn_index` varchar(500),
`btn1` varchar(500),
`btn_url1` varchar(500),
`btn2` varchar(500),
`btn_url2` varchar(500),
`btn3` varchar(500),
`btn_url3` varchar(500),
`btn4` varchar(500),
`btn_url4` varchar(500),
`btn5` varchar(500),
`btn_url5` varchar(500),
`ad2_text` varchar(100),
`ad2` varchar(500),
`ad_url2` varchar(500),
`mobile` varchar(500),
`title1` varchar(500),
`title2` varchar(500),
`qrcode` varchar(500),
`ad` varchar(500),
`ad_url` varchar(500),
`share_title` varchar(200),
`share_desc` varchar(300),
`share_image` varchar(500),
`share_url` varchar(500),
`copyright` varchar(1000),
`dateline` int(10),
`taste_vip` int(10) NOT NULL,
`price1` varchar(20),
`price2` varchar(20),
`price3` varchar(20),
`price4` varchar(20),
`is_secondary_show` tinyint(1) unsigned NOT NULL,
`allowweixin` tinyint(1) NOT NULL,
`viptype` tinyint(1) NOT NULL,
`paytype` tinyint(1) NOT NULL,
`weixin` varchar(50),
`read_min` int(10) NOT NULL,
`read_max` int(10) NOT NULL,
`praise_min` int(10) NOT NULL,
`praise_max` int(10) NOT NULL,
`show_qrcode` tinyint(1) NOT NULL,
`show_mobile` tinyint(1) NOT NULL,
`admode` tinyint(1) NOT NULL,
`is_check` tinyint(1) unsigned NOT NULL,
`btn_link4` varchar(500),
`qq` varchar(255),
`apptitle` varchar(500),
`istplnotice` varchar(500),
`tplneworder` varchar(500),
`notice_openid` varchar(500),
`wechat` varchar(500),
`alipay` varchar(500),
`credit` varchar(500),
`delivery` varchar(500),
`weixin_qrcode` varchar(500),
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_weisrc_quickad_sn` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`uniacid` int(11),
`sncode` varchar(100),
`fansid` int(11),
`from_user` varchar(100),
`status` tinyint(1),
`dateline` int(10),
PRIMARY KEY (`id`),
KEY `indx_id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

");
