<?php
pdo_query("CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_blacklist` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(11),
`type` varchar(1),
`value` varchar(50),
`content` varchar(50),
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
UNIQUE KEY `content` (`content`),
KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_count` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(11),
`rid` int(10) unsigned NOT NULL,
`tid` int(10) unsigned NOT NULL,
`pv_total` int(1) NOT NULL,
`share_total` int(1) NOT NULL,
PRIMARY KEY (`id`),
KEY `indx_uniacid` (`uniacid`),
KEY `indx_rid` (`rid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_domainlist` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`uniacid` int(11),
`rid` int(11),
`type` tinyint(1),
`domain` varchar(50),
`extensive` tinyint(1),
`description` varchar(255) NOT NULL,
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
KEY `content` (`domain`),
KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_gift` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`tid` int(10) unsigned NOT NULL,
`ptid` varchar(128) NOT NULL,
`rid` int(10) unsigned NOT NULL,
`uniacid` int(11),
`uniontid` varchar(30) NOT NULL,
`paytype` varchar(20) NOT NULL,
`oauth_openid` varchar(50) NOT NULL,
`openid` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`nickname` varchar(50) NOT NULL,
`user_ip` varchar(15) NOT NULL,
`gifttitle` varchar(8),
`giftcount` int(10) NOT NULL,
`gifticon` varchar(255) NOT NULL,
`fee` decimal(10,2) NOT NULL,
`giftvote` varchar(50) NOT NULL,
`ispay` int(1) NOT NULL,
`isdeal` tinyint(1) NOT NULL,
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
KEY `indx_tid` (`tid`),
KEY `indx_rid` (`rid`),
KEY `indx_ptid` (`ptid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_redpack` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`tid` int(10) unsigned NOT NULL,
`rid` int(10) unsigned NOT NULL,
`uniacid` int(11),
`unionid` varchar(50) NOT NULL,
`openid` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`nickname` varchar(50) NOT NULL,
`user_ip` varchar(15) NOT NULL,
`mch_billno` varchar(28),
`total_amount` int(10),
`total_num` int(3) NOT NULL,
`client_ip` varchar(15) NOT NULL,
`send_time` varchar(14),
`send_listid` varchar(32),
`return_data` text,
`return_code` varchar(16) NOT NULL,
`return_msg` varchar(256) NOT NULL,
`result_code` varchar(16) NOT NULL,
`err_code` varchar(32) NOT NULL,
`err_code_des` varchar(128) NOT NULL,
`rewards` varchar(20),
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_reply` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`rid` int(10) unsigned NOT NULL,
`uniacid` int(11),
`title` varchar(100),
`thumb` varchar(255),
`description` varchar(255),
`starttime` int(10),
`endtime` int(10),
`apstarttime` int(10),
`apendtime` int(10),
`votestarttime` int(10),
`voteendtime` int(10),
`topimg` varchar(255),
`bgcolor` varchar(255),
`style` varchar(255),
`infomsg` mediumtext,
`eventrule` mediumtext,
`prizemsg` mediumtext,
`endintro` mediumtext,
`config` mediumtext,
`addata` mediumtext,
`giftdata` mediumtext NOT NULL,
`bill_data` mediumtext NOT NULL,
`applydata` mediumtext NOT NULL,
`area` varchar(100),
`shareimg` varchar(255),
`sharetitle` varchar(100),
`sharedesc` varchar(300),
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
KEY `indx_rid` (`rid`),
KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_votedata` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`tid` int(10) unsigned NOT NULL,
`rid` int(10) unsigned NOT NULL,
`uniacid` int(11),
`oauth_openid` varchar(50) NOT NULL,
`openid` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`nickname` varchar(50) NOT NULL,
`user_ip` varchar(15) NOT NULL,
`votetype` tinyint(1),
`reward` tinyint(1) NOT NULL,
`status` tinyint(1),
`createtime` int(10),
PRIMARY KEY (`id`),
KEY `indx_tid` (`tid`),
KEY `indx_rid` (`rid`),
KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ims_tyzm_diamondvote_voteuser` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`noid` int(10) unsigned NOT NULL,
`rid` int(10) unsigned NOT NULL,
`uniacid` int(11),
`oauth_openid` varchar(50) NOT NULL,
`openid` varchar(50) NOT NULL,
`avatar` varchar(255) NOT NULL,
`nickname` varchar(50) NOT NULL,
`user_ip` varchar(15) NOT NULL,
`name` varchar(30) NOT NULL,
`introduction` varchar(255),
`img1` varchar(255),
`img2` varchar(255),
`img3` varchar(255),
`img4` varchar(255),
`img5` varchar(255),
`details` mediumtext,
`joindata` mediumtext NOT NULL,
`formatdata` mediumtext,
`votenum` decimal(10,2) NOT NULL,
`giftcount` decimal(10,2) NOT NULL,
`vheat` int(11) NOT NULL,
`status` tinyint(1),
`locktime` int(10),
`attestation` tinyint(1),
`atmsg` varchar(255) NOT NULL,
`lastvotetime` int(10) NOT NULL,
`createtime` int(10),
PRIMARY KEY (`id`),
KEY `indx_rid` (`rid`),
KEY `indx_uniacid` (`uniacid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

");
